### PR TITLE
Articles | Added date and user id to articles index

### PR DESCRIPTION
**Pull request by xQuByte**
Added propertly reading date and member id (i forgot function to show username)

### CODE REVIEW

**Comment by brunnopleffken** [comment]
I think I forgot this hard-coded username/date. Thanks! ;)

**Comment by xQuByte** [comment]
I am still correcting articles and adding new features ;)

**Comment by brunnopleffken** [comment]
@xQuByte Thanks man! Let's keep it going... 😃 
About articles everything is a little raw, there's still some work to do before getting it into production.

**Comment by xQuByte** [comment]
Yeah, but i need this raw to efficent work ;)
Please send me a db schema for articles

**Pull request merged**
